service:
  type: ClusterIP
  port: 80
  annotations: {}

autoscaling:
  enabled: false

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true

ingress:
  enabled: true
  hosts:  # The host to forward requests to
    - host: "app1.com"  # Hostname for the Ingress
      paths:
        - path: "/"  # Path to match, here we are routing all paths
          pathType: Prefix  # Optional: can be "Prefix" or "Exact"