apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app1
  template:
    metadata:
      labels:
        name: app1
    spec:
      containers:
      - name: app1
        image: "ranarajput/devops-registry:app1-latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: docker-registry-secret
