apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    {{- include "app1.labels" . | nindent 4 }}  # Using app1.labels for common labels
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "app1.selectorLabels" . | nindent 8 }}  # Using app1.selectorLabels for selector
  template:
    metadata:
      labels:
        name: app1
    spec:
      containers:
      - name: app1
        image: "ranarajput/devops-registry:app1-latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: docker-registry-secret
